name: Mirror Commits
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WF_TOKEN }}
      - name: Mirror commits
        run: |
          git remote add upstream https://github.com/cosmos/chain-registry
          git fetch
          git fetch upstream
          git checkout mirror
          git pull upstream master
          git push origin mirror
