on: [pull_request, workflow_dispatch]
name: PR workflow
jobs:
  validate_chainjson:
    name: Validate edited chains.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate Chain.json schema
        run: find . -name '*chain.json' -exec jsonschema -i {} -s ./chain.schema.json \;
