on: [pull_request, workflow_dispatch]
name: PR workflow
jobs:
  validate_ibcdatajson:
    name: Validate ibc data schemas
    runs-on: ubuntu-latest
    steps:
      - name: checkout registry
        uses: actions/checkout@v3

      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate IBC data schemas
        run: find . -name '*/_IBC/*.json' -exec jsonschema -i {} -s ./ibc-data.schema.json \;

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run:  |
          python -m pip install --upgrade pip
          cd .github/workflows/utility
          pip install pytest==7.1.2

      - name: Chain Name Validation
        run:   |
          python -m pytest --import-mode=append .github/workflows/utility
